In [3]:
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("default")
import csv, sqlite3

In [4]:
conn = sqlite3.connect("RealWorldData.db")
cur = conn.cursor()

In [5]:
%load_ext sql 
%sql sqlite:///RealWorldData.db

In [6]:
df = pd.read_csv("D:\PROGRAMMING\DATASETS\ChicagoPublicSchools.csv")
print(df.shape)
df.head()

(566, 78)

,School_ID,NAME_OF_SCHOOL,"Elementary, Middle, or High School",Street_Address,City,State,ZIP_Code,Phone_Number,Link,Network_Manager,...,Freshman_on_Track_Rate__,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,Ward,Police_District,Location
0,610038,Abraham Lincoln Elementary School,ES,615 W Kemper Pl,Chicago,IL,60614,(773) 534-5720,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,NDA,1171699.458,1915829.428,41.924497,-87.644522,7,LINCOLN PARK,43,18,"(41.92449696, -87.64452163)"
1,610281,Adam Clayton Powell Paideia Community Academy ...,ES,7511 S South Shore Dr,Chicago,IL,60649,(773) 535-6650,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1196129.985,1856209.466,41.760324,-87.556736,43,SOUTH SHORE,7,4,"(41.76032435, -87.55673627)"
2,610185,Adlai E Stevenson Elementary School,ES,8010 S Kostner Ave,Chicago,IL,60652,(773) 535-2280,http://schoolreports.cps.edu/SchoolProgressRep...,Midway Elementary Network,...,NDA,1148427.165,1851012.215,41.747111,-87.731702,70,ASHBURN,13,8,"(41.74711093, -87.73170248)"
3,609993,Agustin Lara Elementary Academy,ES,4619 S Wolcott Ave,Chicago,IL,60609,(773) 535-4389,http://schoolreports.cps.edu/SchoolProgressRep...,Pershing Elementary Network,...,NDA,1164504.290,1873959.199,41.809757,-87.672145,61,NEW CITY,20,9,"(41.8097569, -87.6721446)"
4,610513,Air Force Academy High School,HS,3630 S Wells St,Chicago,IL,60609,(773) 535-1590,http://schoolreports.cps.edu/SchoolProgressRep...,Southwest Side High School Network,...,91.8,1175177.622,1880745.126,41.828146,-87.632794,34,ARMOUR SQUARE,11,9,"(41.82814609, -87.63279369)"

In [7]:
chunksize = 100  # You can adjust this based on your data size
for i in range(0, len(df), chunksize):
    df.iloc[i:i+chunksize].to_sql("Chicago_School_Data", conn, if_exists='append', index=False)

In [8]:
%sql SELECT * FROM Chicago_School_Data LIMIT 10;

 * sqlite:///RealWorldData.db
Done.

[(610038, 'Abraham Lincoln Elementary School', 'ES', '615 W Kemper Pl', 'Chicago', 'IL', 60614, '(773) 534-5720', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610038.pdf', 'Fullerton Elementary Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 1', 'Yes', 'Very Strong', 99.0, 'Very Strong', '99', 'Strong', 74.0, 'Strong', 66.0, 'Weak', '65', 'Strong', '70', 'Strong', '56', 'Average', '47', '96.00%', 2.0, '96.40%', '95.80%', '80.1', '43.3', '89.6', '84.9', '60.7', '62.6', '81.9', '85.2', '52', '62.4', '66.3', '77.9', 69.7, 64.4, 0.2, 0.9, 'Yellow', 'Green', '67.1', '54.5', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 813, 33, 'NDA', 1171699.458, 1915829.428, 41.92449696, -87.64452163, 7, 'LINCOLN PARK', 43, 18, '(41.92449696, -87.64452163)'),
 (610281, 'Adam Clayton Powell Paideia Community Academy Elementary School', 'ES', '7511 S South Shore Dr', 'Chicago', 'IL', 60649, '(773) 535-6650', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610281.pdf', 'Skyway Elementary Network', 'SOUTH SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', 54.0, 'Strong', '66', 'Strong', 74.0, 'Very Strong', 84.0, 'Weak', '63', 'Strong', '76', 'Weak', '46', 'Average', '50', '95.60%', 15.7, '95.30%', '100.00%', '62.4', '51.7', '21.9', '15.1', '29', '42.8', '38.5', '27.4', '44.8', '42.7', '14.1', '34.4', 16.8, 16.5, 0.7, 1.4, 'Green', 'Green', '17.2', '27.3', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 521, 46, 'NDA', 1196129.985, 1856209.466, 41.76032435, -87.55673627, 43, 'SOUTH SHORE', 7, 4, '(41.76032435, -87.55673627)'),
 (610185, 'Adlai E Stevenson Elementary School', 'ES', '8010 S Kostner Ave', 'Chicago', 'IL', 60652, '(773) 535-2280', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610185.pdf', 'Midway Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 2', 'No', 'Strong', 61.0, 'NDA', 'NDA', 'Average', 50.0, 'Weak', 36.0, 'Weak', 'NDA', 'NDA', 'NDA', 'Average', '47', 'Weak', '41', '95.70%', 2.3, '94.70%', '98.30%', '53.7', '26.6', '38.3', '34.7', '43.7', '57.3', '48.8', '39.2', '46.8', '44', '7.5', '21.9', 18.3, 15.5, -0.9, -1.0, 'Red', 'Red', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 1324, 44, 'NDA', 1148427.165, 1851012.215, 41.74711093, -87.73170248, 70, 'ASHBURN', 13, 8, '(41.74711093, -87.73170248)'),
 (609993, 'Agustin Lara Elementary Academy', 'ES', '4619 S Wolcott Ave', 'Chicago', 'IL', 60609, '(773) 535-4389', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609993.pdf', 'Pershing Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', 56.0, 'Average', '44', 'Average', 45.0, 'Weak', 37.0, 'Weak', '65', 'Average', '48', 'Average', '53', 'Strong', '58', '95.50%', 10.4, '95.80%', '100.00%', '76.9', 'NDA', '26', '24.7', '61.8', '49.7', '39.2', '27.2', '69.7', '60.6', '9.1', '18.2', 11.1, 9.6, 0.9, 2.4, 'Green', 'Green', '42.9', '25', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 556, 42, 'NDA', 1164504.29, 1873959.199, 41.8097569, -87.6721446, 61, 'NEW CITY', 20, 9, '(41.8097569, -87.6721446)'),
 (610513, 'Air Force Academy High School', 'HS', '3630 S Wells St', 'Chicago', 'IL', 60609, '(773) 535-1590', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610513.pdf', 'Southwest Side High School Network', 'SOUTHWEST SIDE COLLABORATIVE', 'NDA', 'Standard', 'Not on Probation', 'Not Enough Data', 'Yes', 'Average', 49.0, 'Strong', '60', 'Strong', 60.0, 'Average', 55.0, 'Weak', '45', 'Average', '54', 'Average', '53', 'Average', '49', '93.30%', 15.6, '96.90%', '100.00%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', None, None, None, None, 'NDA', 'NDA', 'NDA', 'NDA', '14.6', '14.8', 'NDA', '16', '1.4', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 302, 40, '91.8', 1175177.622, 1880745.126, 41.82814609, -87.63279369, 34, 'ARMOUR SQUARE', 11, 9, '(41.82814609, -87.63279369)'),
 (610212, 'Albany Park Multicultural Academy', 'MS', '4929 N Sawyer Ave', 'Chicago', 'IL', 60625, '(773) 534-5108', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610212.pdf', "O'Hare Elementary Network", 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'Yes', 'Standard', 'Not on Probation', 'Level 1', 'No', 'Strong', 66.0, 'Weak', '37', 'Strong', 66.0, 'Strong', 71.0, 'Weak', '43', 'Average', '50', 'Weak', '46', 'Average', '51', '97.00%', 2.3, '96.90%', '100.00%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '60.7', '39.8', '53.7', '59.8', '17.5', '20.8', 34.5, 15.6, 0.2, 0.3, 'Yellow', 'Yellow', '29.2', '50', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 266, 31, 'NDA', 1153858.196, 1932691.891, 41.9711433, -87.70962725, 14, 'ALBANY PARK', 39, 17, '(41.9711433, -87.70962725)'),
 (609720, 'Albert G Lane Technical High School', 'HS', '2501 W Addison St', 'Chicago', 'IL', 60618, '(773) 534-5400', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609720.pdf', 'North-Northwest Side High School Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'Yes', 'Standard', 'Not on Probation', 'Level 1', 'No', 'Very Strong', 88.0, 'NDA', 'NDA', 'Strong', 62.0, 'Average', 52.0, 'Weak', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '96.30%', 2.1, '96.20%', '99.40%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', None, None, None, None, 'NDA', 'NDA', 'NDA', 'NDA', '19.1', '19.5', '19.9', '20.1', '1', '23.4', '3.5', '67.9', '92.2', '79.8', 4368, 35, '90.7', 1158975.392, 1923791.705, 41.94661693, -87.69105603, 5, 'NORTH CENTER', 47, 19, '(41.94661693, -87.69105603)'),
 (610342, 'Albert R Sabin Elementary Magnet School', 'ES', '2216 W Hirsch St', 'Chicago', 'IL', 60622, '(773) 534-4491', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610342.pdf', 'Fulton Elementary Network', 'WEST SIDE COLLABORATIVE', 'No', 'Standard', 'Probation', 'Level 3', 'No', 'Strong', 67.0, 'NDA', 'NDA', 'Weak', 30.0, 'Very Weak', 18.0, 'Weak', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '94.70%', 28.1, '95.00%', '100.00%', '56.3', 'NDA', '33.5', '33.5', '49.5', '49.5', '27.4', '39.3', '35.5', '44.4', '25', '23.4', 18.0, 12.8, -1.8, 0.1, 'Red', 'Yellow', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 620, 35, 'NDA', 1161265.299, 1909314.592, 41.90684338, -87.68304259, 24, 'WEST TOWN', 1, 14, '(41.90684338, -87.68304259)'),
 (610524, 'Alcott High School for the Humanities', 'HS', '2957 N Hoyne Ave', 'Chicago', 'IL', 60618, '(773) 534-5979', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610524.pdf', 'North-Northwest Side High School Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'NDA', 'Standard', 'Not on Probation', 'Not Enough Data', 'No', 'Strong', 70.0, 'NDA', 'NDA', 'Strong', 67.0, 'Average', 51.0, 'Weak', 'NDA', 'NDA', 'NDA', 'Strong', '57', 'Weak', '43', '92.70%', 7.1, '96.90%', '100.00%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', None, None, None, None, 'NDA', 'NDA', 'NDA', 'NDA', '14.7', '13.7', 'NDA', '16', '1.3', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 232, 33, '87.6', 1161870.556, 1919857.44, 41.93576106, -87.68052441, 5, 'NORTH CENTER', 1, 19, '(41.93576106, -87.68052441)'),
 (610209, 'Alessandro Volta Elementary School', 'ES', '4950 N Avers Ave', 'Chicago', 'IL', 60625, '(773) 534-5080', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610209.pdf', "O'Hare Elementary Network", 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 2', 'No', 'Average', 43.0, 'Strong', '61', 'Weak', 28.0, 'Weak', 37.0, 'Weak', '62', 'Average', '56', 'Average', '51', 'Average', '53', '96.40%', 22.5, '95.90%', '100.00%', '63.9', '43.2', '51.3', '32.9', '50.7', '70', '52.5', '31.3', '59.8', '57.6', '16.5', '24.7', 19.9, 14.2, 0.3, -0.4, 'Yellow', 'Yellow', '31.6', '65.2', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 1023, 31, 'NDA', 1149774.095, 1932831.151, 41.97160605, -87.72464139, 14, 'ALBANY PARK', 39, 17, '(41.97160605, -87.72464139)')]

In [9]:
%sql SELECT COUNT(*) as "Total_rows" FROM Chicago_School_Data;

 * sqlite:///RealWorldData.db
Done.

[(566,)]

* count the total columns

In [16]:
%sql SELECT COUNT(*) as "Total_Columns" FROM pragma_table_info('Chicago_School_Data');

 * sqlite:///RealWorldData.db
Done.

[(78,)]

* retrieve the column `name`, `datatype` and `type length`

In [17]:
%sql SELECT name, type, length(type) FROM pragma_table_info('Chicago_School_Data');

 * sqlite:///RealWorldData.db
Done.

[('School_ID', 'INTEGER', 7),
 ('NAME_OF_SCHOOL', 'TEXT', 4),
 ('Elementary, Middle, or High School', 'TEXT', 4),
 ('Street_Address', 'TEXT', 4),
 ('City', 'TEXT', 4),
 ('State', 'TEXT', 4),
 ('ZIP_Code', 'INTEGER', 7),
 ('Phone_Number', 'TEXT', 4),
 ('Link', 'TEXT', 4),
 ('Network_Manager', 'TEXT', 4),
 ('Collaborative_Name', 'TEXT', 4),
 ('Adequate_Yearly_Progress_Made_', 'TEXT', 4),
 ('Track_Schedule', 'TEXT', 4),
 ('CPS_Performance_Policy_Status', 'TEXT', 4),
 ('CPS_Performance_Policy_Level', 'TEXT', 4),
 ('HEALTHY_SCHOOL_CERTIFIED', 'TEXT', 4),
 ('Safety_Icon', 'TEXT', 4),
 ('SAFETY_SCORE', 'REAL', 4),
 ('Family_Involvement_Icon', 'TEXT', 4),
 ('Family_Involvement_Score', 'TEXT', 4),
 ('Environment_Icon', 'TEXT', 4),
 ('Environment_Score', 'REAL', 4),
 ('Instruction_Icon', 'TEXT', 4),
 ('Instruction_Score', 'REAL', 4),
 ('Leaders_Icon', 'TEXT', 4),
 ('Leaders_Score', 'TEXT', 4),
 ('Teachers_Icon', 'TEXT', 4),
 ('Teachers_Score', 'TEXT', 4),
 ('Parent_Engagement_Icon', 'TEXT', 4),
 ('Parent_Engagement_Score', 'TEXT', 4),
 ('Parent_Environment_Icon', 'TEXT', 4),
 ('Parent_Environment_Score', 'TEXT', 4),
 ('AVERAGE_STUDENT_ATTENDANCE', 'TEXT', 4),
 ('Rate_of_Misconducts__per_100_students_', 'REAL', 4),
 ('Average_Teacher_Attendance', 'TEXT', 4),
 ('Individualized_Education_Program_Compliance_Rate', 'TEXT', 4),
 ('Pk_2_Literacy__', 'TEXT', 4),
 ('Pk_2_Math__', 'TEXT', 4),
 ('Gr3_5_Grade_Level_Math__', 'TEXT', 4),
 ('Gr3_5_Grade_Level_Read__', 'TEXT', 4),
 ('Gr3_5_Keep_Pace_Read__', 'TEXT', 4),
 ('Gr3_5_Keep_Pace_Math__', 'TEXT', 4),
 ('Gr6_8_Grade_Level_Math__', 'TEXT', 4),
 ('Gr6_8_Grade_Level_Read__', 'TEXT', 4),
 ('Gr6_8_Keep_Pace_Math_', 'TEXT', 4),
 ('Gr6_8_Keep_Pace_Read__', 'TEXT', 4),
 ('Gr_8_Explore_Math__', 'TEXT', 4),
 ('Gr_8_Explore_Read__', 'TEXT', 4),
 ('ISAT_Exceeding_Math__', 'REAL', 4),
 ('ISAT_Exceeding_Reading__', 'REAL', 4),
 ('ISAT_Value_Add_Math', 'REAL', 4),
 ('ISAT_Value_Add_Read', 'REAL', 4),
 ('ISAT_Value_Add_Color_Math', 'TEXT', 4),
 ('ISAT_Value_Add_Color_Read', 'TEXT', 4),
 ('Students_Taking__Algebra__', 'TEXT', 4),
 ('Students_Passing__Algebra__', 'TEXT', 4),
 ('9th Grade EXPLORE (2009)', 'TEXT', 4),
 ('9th Grade EXPLORE (2010)', 'TEXT', 4),
 ('10th Grade PLAN (2009)', 'TEXT', 4),
 ('10th Grade PLAN (2010)', 'TEXT', 4),
 ('Net_Change_EXPLORE_and_PLAN', 'TEXT', 4),
 ('11th Grade Average ACT (2011)', 'TEXT', 4),
 ('Net_Change_PLAN_and_ACT', 'TEXT', 4),
 ('College_Eligibility__', 'TEXT', 4),
 ('Graduation_Rate__', 'TEXT', 4),
 ('College_Enrollment_Rate__', 'TEXT', 4),
 ('COLLEGE_ENROLLMENT', 'INTEGER', 7),
 ('General_Services_Route', 'INTEGER', 7),
 ('Freshman_on_Track_Rate__', 'TEXT', 4),
 ('X_COORDINATE', 'REAL', 4),
 ('Y_COORDINATE', 'REAL', 4),
 ('Latitude', 'REAL', 4),
 ('Longitude', 'REAL', 4),
 ('COMMUNITY_AREA_NUMBER', 'INTEGER', 7),
 ('COMMUNITY_AREA_NAME', 'TEXT', 4),
 ('Ward', 'INTEGER', 7),
 ('Police_District', 'INTEGER', 7),
 ('Location', 'TEXT', 4)]

In [21]:
%sql SELECT name, type, length(type) FROM pragma_table_info('Chicago_School_Data') \
WHERE type = 'INTEGER';

 * sqlite:///RealWorldData.db
Done.

[('School_ID', 'INTEGER', 7),
 ('ZIP_Code', 'INTEGER', 7),
 ('COLLEGE_ENROLLMENT', 'INTEGER', 7),
 ('General_Services_Route', 'INTEGER', 7),
 ('COMMUNITY_AREA_NUMBER', 'INTEGER', 7),
 ('Ward', 'INTEGER', 7),
 ('Police_District', 'INTEGER', 7)]

In [22]:
%sql SELECT DISTINCT type FROM pragma_table_info('Chicago_School_Data');

 * sqlite:///RealWorldData.db
Done.

[('INTEGER',), ('TEXT',), ('REAL',)]

In [24]:
%sql SELECT * FROM Chicago_School_Data LIMIT 5;

 * sqlite:///RealWorldData.db
Done.

[(610038, 'Abraham Lincoln Elementary School', 'ES', '615 W Kemper Pl', 'Chicago', 'IL', 60614, '(773) 534-5720', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610038.pdf', 'Fullerton Elementary Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 1', 'Yes', 'Very Strong', 99.0, 'Very Strong', '99', 'Strong', 74.0, 'Strong', 66.0, 'Weak', '65', 'Strong', '70', 'Strong', '56', 'Average', '47', '96.00%', 2.0, '96.40%', '95.80%', '80.1', '43.3', '89.6', '84.9', '60.7', '62.6', '81.9', '85.2', '52', '62.4', '66.3', '77.9', 69.7, 64.4, 0.2, 0.9, 'Yellow', 'Green', '67.1', '54.5', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 813, 33, 'NDA', 1171699.458, 1915829.428, 41.92449696, -87.64452163, 7, 'LINCOLN PARK', 43, 18, '(41.92449696, -87.64452163)'),
 (610281, 'Adam Clayton Powell Paideia Community Academy Elementary School', 'ES', '7511 S South Shore Dr', 'Chicago', 'IL', 60649, '(773) 535-6650', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610281.pdf', 'Skyway Elementary Network', 'SOUTH SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', 54.0, 'Strong', '66', 'Strong', 74.0, 'Very Strong', 84.0, 'Weak', '63', 'Strong', '76', 'Weak', '46', 'Average', '50', '95.60%', 15.7, '95.30%', '100.00%', '62.4', '51.7', '21.9', '15.1', '29', '42.8', '38.5', '27.4', '44.8', '42.7', '14.1', '34.4', 16.8, 16.5, 0.7, 1.4, 'Green', 'Green', '17.2', '27.3', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 521, 46, 'NDA', 1196129.985, 1856209.466, 41.76032435, -87.55673627, 43, 'SOUTH SHORE', 7, 4, '(41.76032435, -87.55673627)'),
 (610185, 'Adlai E Stevenson Elementary School', 'ES', '8010 S Kostner Ave', 'Chicago', 'IL', 60652, '(773) 535-2280', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610185.pdf', 'Midway Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 2', 'No', 'Strong', 61.0, 'NDA', 'NDA', 'Average', 50.0, 'Weak', 36.0, 'Weak', 'NDA', 'NDA', 'NDA', 'Average', '47', 'Weak', '41', '95.70%', 2.3, '94.70%', '98.30%', '53.7', '26.6', '38.3', '34.7', '43.7', '57.3', '48.8', '39.2', '46.8', '44', '7.5', '21.9', 18.3, 15.5, -0.9, -1.0, 'Red', 'Red', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 1324, 44, 'NDA', 1148427.165, 1851012.215, 41.74711093, -87.73170248, 70, 'ASHBURN', 13, 8, '(41.74711093, -87.73170248)'),
 (609993, 'Agustin Lara Elementary Academy', 'ES', '4619 S Wolcott Ave', 'Chicago', 'IL', 60609, '(773) 535-4389', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609993.pdf', 'Pershing Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', 56.0, 'Average', '44', 'Average', 45.0, 'Weak', 37.0, 'Weak', '65', 'Average', '48', 'Average', '53', 'Strong', '58', '95.50%', 10.4, '95.80%', '100.00%', '76.9', 'NDA', '26', '24.7', '61.8', '49.7', '39.2', '27.2', '69.7', '60.6', '9.1', '18.2', 11.1, 9.6, 0.9, 2.4, 'Green', 'Green', '42.9', '25', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 556, 42, 'NDA', 1164504.29, 1873959.199, 41.8097569, -87.6721446, 61, 'NEW CITY', 20, 9, '(41.8097569, -87.6721446)'),
 (610513, 'Air Force Academy High School', 'HS', '3630 S Wells St', 'Chicago', 'IL', 60609, '(773) 535-1590', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610513.pdf', 'Southwest Side High School Network', 'SOUTHWEST SIDE COLLABORATIVE', 'NDA', 'Standard', 'Not on Probation', 'Not Enough Data', 'Yes', 'Average', 49.0, 'Strong', '60', 'Strong', 60.0, 'Average', 55.0, 'Weak', '45', 'Average', '54', 'Average', '53', 'Average', '49', '93.30%', 15.6, '96.90%', '100.00%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', None, None, None, None, 'NDA', 'NDA', 'NDA', 'NDA', '14.6', '14.8', 'NDA', '16', '1.4', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 302, 40, '91.8', 1175177.622, 1880745.126, 41.82814609, -87.63279369, 34, 'ARMOUR SQUARE', 11, 9, '(41.82814609, -87.63279369)')]

* How many `Elementary Schools` are these in the dataset?

In [32]:
%%sql
SELECT COUNT(*) as "Total_Elementary_Schools" 
FROM Chicago_School_Data 
WHERE "Elementary, Middle, or High School" = 'ES';

 * sqlite:///RealWorldData.db
Done.

[(462,)]

* Counting the `Frequency` of Schools

In [34]:
%%sql

SELECT "Elementary, Middle, or High School" as "School_Names", COUNT(*) as "Frequency"
FROM Chicago_School_Data
GROUP BY "Elementary, Middle, or High School"
ORDER BY Frequency;

 * sqlite:///RealWorldData.db
Done.

[('MS', 11), ('HS', 93), ('ES', 462)]

In [36]:
%sql SELECT MAX("safety_score") FROM Chicago_School_Data;

 * sqlite:///RealWorldData.db
Done.

[(99.0,)]

In [37]:
%sql SELECT "name_of_school", MAX("safety_score") FROM Chicago_School_Data;

 * sqlite:///RealWorldData.db
Done.

[('Abraham Lincoln Elementary School', 99.0)]

* What are `Top 10` schools with `highest` Average Student Attendance?

In [38]:
%%sql 
SELECT "name_of_school", "average_student_attendance" 
from Chicago_School_Data
ORDER BY "average_student_attendance" DESC
LIMIT 10;

 * sqlite:///RealWorldData.db
Done.

[('John Charles Haines Elementary School', '98.40%'),
 ('James Ward Elementary School', '97.80%'),
 ('Edgar Allan Poe Elementary Classical School', '97.60%'),
 ('Orozco Fine Arts & Sciences Elementary School', '97.60%'),
 ('Rachel Carson Elementary School', '97.60%'),
 ('Annie Keller Elementary Gifted Magnet School', '97.50%'),
 ('Andrew Jackson Elementary Language Academy', '97.40%'),
 ('Lenart Elementary Regional Gifted Center', '97.40%'),
 ('Disney II Magnet School', '97.30%'),
 ('John H Vanderpoel Elementary Magnet School', '97.20%')]

* What are `Top 10` schools with `lowest` Average Student Attendance?

In [40]:
%%sql
SELECT "name_of_school" as "School", "average_student_attendance" as "average_attendance"
FROM Chicago_School_Data
ORDER BY "average_attendance"
LIMIT 10;

 * sqlite:///RealWorldData.db
Done.

[('Velma F Thomas Early Childhood Center', None),
 ('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%'),
 ('Orr Academy High School', '66.30%'),
 ('Manley Career Academy High School', '66.80%'),
 ('Chicago Vocational Career Academy High School', '68.80%'),
 ('Roberto Clemente Community Academy High School', '69.60%'),
 ('Austin Polytechnical Academy High School', '70.10%')]

In [41]:
%%sql

SELECT "name_of_school" as "School", REPLACE("average_student_attendance", '%', '') as "average_attendance"
FROM Chicago_School_Data
ORDER BY "average_attendance"
LIMIT 10;

 * sqlite:///RealWorldData.db
Done.

[('Velma F Thomas Early Childhood Center', None),
 ('Richard T Crane Technical Preparatory High School', '57.90'),
 ('Barbara Vick Early Childhood & Family Center', '60.90'),
 ('Dyett High School', '62.50'),
 ('Wendell Phillips Academy High School', '63.00'),
 ('Orr Academy High School', '66.30'),
 ('Manley Career Academy High School', '66.80'),
 ('Chicago Vocational Career Academy High School', '68.80'),
 ('Roberto Clemente Community Academy High School', '69.60'),
 ('Austin Polytechnical Academy High School', '70.10')]

In [42]:
%%sql

SELECT "name_of_school" as "School", "average_student_attendance" as "average_attendance"
FROM Chicago_School_Data
WHERE "average_student_attendance" <= 70;

 * sqlite:///RealWorldData.db
Done.

[('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Chicago Vocational Career Academy High School', '68.80%'),
 ('Dyett High School', '62.50%'),
 ('Manley Career Academy High School', '66.80%'),
 ('Orr Academy High School', '66.30%'),
 ('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Roberto Clemente Community Academy High School', '69.60%'),
 ('Wendell Phillips Academy High School', '63.00%')]

In [43]:
%sql SELECT * FROM Chicago_School_Data LIMIT 10;

 * sqlite:///RealWorldData.db
Done.

[(610038, 'Abraham Lincoln Elementary School', 'ES', '615 W Kemper Pl', 'Chicago', 'IL', 60614, '(773) 534-5720', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610038.pdf', 'Fullerton Elementary Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 1', 'Yes', 'Very Strong', 99.0, 'Very Strong', '99', 'Strong', 74.0, 'Strong', 66.0, 'Weak', '65', 'Strong', '70', 'Strong', '56', 'Average', '47', '96.00%', 2.0, '96.40%', '95.80%', '80.1', '43.3', '89.6', '84.9', '60.7', '62.6', '81.9', '85.2', '52', '62.4', '66.3', '77.9', 69.7, 64.4, 0.2, 0.9, 'Yellow', 'Green', '67.1', '54.5', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 813, 33, 'NDA', 1171699.458, 1915829.428, 41.92449696, -87.64452163, 7, 'LINCOLN PARK', 43, 18, '(41.92449696, -87.64452163)'),
 (610281, 'Adam Clayton Powell Paideia Community Academy Elementary School', 'ES', '7511 S South Shore Dr', 'Chicago', 'IL', 60649, '(773) 535-6650', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610281.pdf', 'Skyway Elementary Network', 'SOUTH SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', 54.0, 'Strong', '66', 'Strong', 74.0, 'Very Strong', 84.0, 'Weak', '63', 'Strong', '76', 'Weak', '46', 'Average', '50', '95.60%', 15.7, '95.30%', '100.00%', '62.4', '51.7', '21.9', '15.1', '29', '42.8', '38.5', '27.4', '44.8', '42.7', '14.1', '34.4', 16.8, 16.5, 0.7, 1.4, 'Green', 'Green', '17.2', '27.3', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 521, 46, 'NDA', 1196129.985, 1856209.466, 41.76032435, -87.55673627, 43, 'SOUTH SHORE', 7, 4, '(41.76032435, -87.55673627)'),
 (610185, 'Adlai E Stevenson Elementary School', 'ES', '8010 S Kostner Ave', 'Chicago', 'IL', 60652, '(773) 535-2280', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610185.pdf', 'Midway Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 2', 'No', 'Strong', 61.0, 'NDA', 'NDA', 'Average', 50.0, 'Weak', 36.0, 'Weak', 'NDA', 'NDA', 'NDA', 'Average', '47', 'Weak', '41', '95.70%', 2.3, '94.70%', '98.30%', '53.7', '26.6', '38.3', '34.7', '43.7', '57.3', '48.8', '39.2', '46.8', '44', '7.5', '21.9', 18.3, 15.5, -0.9, -1.0, 'Red', 'Red', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 1324, 44, 'NDA', 1148427.165, 1851012.215, 41.74711093, -87.73170248, 70, 'ASHBURN', 13, 8, '(41.74711093, -87.73170248)'),
 (609993, 'Agustin Lara Elementary Academy', 'ES', '4619 S Wolcott Ave', 'Chicago', 'IL', 60609, '(773) 535-4389', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609993.pdf', 'Pershing Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', 56.0, 'Average', '44', 'Average', 45.0, 'Weak', 37.0, 'Weak', '65', 'Average', '48', 'Average', '53', 'Strong', '58', '95.50%', 10.4, '95.80%', '100.00%', '76.9', 'NDA', '26', '24.7', '61.8', '49.7', '39.2', '27.2', '69.7', '60.6', '9.1', '18.2', 11.1, 9.6, 0.9, 2.4, 'Green', 'Green', '42.9', '25', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 556, 42, 'NDA', 1164504.29, 1873959.199, 41.8097569, -87.6721446, 61, 'NEW CITY', 20, 9, '(41.8097569, -87.6721446)'),
 (610513, 'Air Force Academy High School', 'HS', '3630 S Wells St', 'Chicago', 'IL', 60609, '(773) 535-1590', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610513.pdf', 'Southwest Side High School Network', 'SOUTHWEST SIDE COLLABORATIVE', 'NDA', 'Standard', 'Not on Probation', 'Not Enough Data', 'Yes', 'Average', 49.0, 'Strong', '60', 'Strong', 60.0, 'Average', 55.0, 'Weak', '45', 'Average', '54', 'Average', '53', 'Average', '49', '93.30%', 15.6, '96.90%', '100.00%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', None, None, None, None, 'NDA', 'NDA', 'NDA', 'NDA', '14.6', '14.8', 'NDA', '16', '1.4', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 302, 40, '91.8', 1175177.622, 1880745.126, 41.82814609, -87.63279369, 34, 'ARMOUR SQUARE', 11, 9, '(41.82814609, -87.63279369)'),
 (610212, 'Albany Park Multicultural Academy', 'MS', '4929 N Sawyer Ave', 'Chicago', 'IL', 60625, '(773) 534-5108', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610212.pdf', "O'Hare Elementary Network", 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'Yes', 'Standard', 'Not on Probation', 'Level 1', 'No', 'Strong', 66.0, 'Weak', '37', 'Strong', 66.0, 'Strong', 71.0, 'Weak', '43', 'Average', '50', 'Weak', '46', 'Average', '51', '97.00%', 2.3, '96.90%', '100.00%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '60.7', '39.8', '53.7', '59.8', '17.5', '20.8', 34.5, 15.6, 0.2, 0.3, 'Yellow', 'Yellow', '29.2', '50', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 266, 31, 'NDA', 1153858.196, 1932691.891, 41.9711433, -87.70962725, 14, 'ALBANY PARK', 39, 17, '(41.9711433, -87.70962725)'),
 (609720, 'Albert G Lane Technical High School', 'HS', '2501 W Addison St', 'Chicago', 'IL', 60618, '(773) 534-5400', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609720.pdf', 'North-Northwest Side High School Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'Yes', 'Standard', 'Not on Probation', 'Level 1', 'No', 'Very Strong', 88.0, 'NDA', 'NDA', 'Strong', 62.0, 'Average', 52.0, 'Weak', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '96.30%', 2.1, '96.20%', '99.40%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', None, None, None, None, 'NDA', 'NDA', 'NDA', 'NDA', '19.1', '19.5', '19.9', '20.1', '1', '23.4', '3.5', '67.9', '92.2', '79.8', 4368, 35, '90.7', 1158975.392, 1923791.705, 41.94661693, -87.69105603, 5, 'NORTH CENTER', 47, 19, '(41.94661693, -87.69105603)'),
 (610342, 'Albert R Sabin Elementary Magnet School', 'ES', '2216 W Hirsch St', 'Chicago', 'IL', 60622, '(773) 534-4491', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610342.pdf', 'Fulton Elementary Network', 'WEST SIDE COLLABORATIVE', 'No', 'Standard', 'Probation', 'Level 3', 'No', 'Strong', 67.0, 'NDA', 'NDA', 'Weak', 30.0, 'Very Weak', 18.0, 'Weak', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '94.70%', 28.1, '95.00%', '100.00%', '56.3', 'NDA', '33.5', '33.5', '49.5', '49.5', '27.4', '39.3', '35.5', '44.4', '25', '23.4', 18.0, 12.8, -1.8, 0.1, 'Red', 'Yellow', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 620, 35, 'NDA', 1161265.299, 1909314.592, 41.90684338, -87.68304259, 24, 'WEST TOWN', 1, 14, '(41.90684338, -87.68304259)'),
 (610524, 'Alcott High School for the Humanities', 'HS', '2957 N Hoyne Ave', 'Chicago', 'IL', 60618, '(773) 534-5979', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610524.pdf', 'North-Northwest Side High School Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'NDA', 'Standard', 'Not on Probation', 'Not Enough Data', 'No', 'Strong', 70.0, 'NDA', 'NDA', 'Strong', 67.0, 'Average', 51.0, 'Weak', 'NDA', 'NDA', 'NDA', 'Strong', '57', 'Weak', '43', '92.70%', 7.1, '96.90%', '100.00%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', None, None, None, None, 'NDA', 'NDA', 'NDA', 'NDA', '14.7', '13.7', 'NDA', '16', '1.3', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 232, 33, '87.6', 1161870.556, 1919857.44, 41.93576106, -87.68052441, 5, 'NORTH CENTER', 1, 19, '(41.93576106, -87.68052441)'),
 (610209, 'Alessandro Volta Elementary School', 'ES', '4950 N Avers Ave', 'Chicago', 'IL', 60625, '(773) 534-5080', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610209.pdf', "O'Hare Elementary Network", 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 2', 'No', 'Average', 43.0, 'Strong', '61', 'Weak', 28.0, 'Weak', 37.0, 'Weak', '62', 'Average', '56', 'Average', '51', 'Average', '53', '96.40%', 22.5, '95.90%', '100.00%', '63.9', '43.2', '51.3', '32.9', '50.7', '70', '52.5', '31.3', '59.8', '57.6', '16.5', '24.7', 19.9, 14.2, 0.3, -0.4, 'Yellow', 'Yellow', '31.6', '65.2', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 1023, 31, 'NDA', 1149774.095, 1932831.151, 41.97160605, -87.72464139, 14, 'ALBANY PARK', 39, 17, '(41.97160605, -87.72464139)')]

* Total college enrollment for each community area

In [45]:
%%sql

SELECT "community_area_name" , SUM("college_enrollment") as "total_college_enrollment"
FROM Chicago_school_Data
GROUP BY "community_area_name"
ORDER BY "total_college_enrollment";

 * sqlite:///RealWorldData.db
Done.

[('OAKLAND', 140),
 ('FULLER PARK', 531),
 ('BURNSIDE', 549),
 ('OHARE', 786),
 ('LOOP', 871),
 ('EDISON PARK', 910),
 ('HEGEWISCH', 963),
 ('MONTCLARE', 1317),
 ('NEAR SOUTH SIDE', 1378),
 ('FOREST GLEN', 1431),
 ('ARMOUR SQUARE', 1458),
 ('AVALON PARK', 1522),
 ('RIVERDALE', 1547),
 ('MCKINLEY PARK', 1552),
 ('CALUMET HEIGHTS', 1568),
 ('PULLMAN', 1620),
 ('BEVERLY', 1636),
 ('JEFFERSON PARK', 1755),
 ('SOUTH DEERING', 1859),
 ('HYDE PARK', 1930),
 ('CLEARING', 2085),
 ('MOUNT GREENWOOD', 2091),
 ('WEST GARFIELD PARK', 2622),
 ('WASHINGTON PARK', 2648),
 ('GRAND BOULEVARD', 2809),
 ('BRIDGEPORT', 3167),
 ('WEST PULLMAN', 3240),
 ('MORGAN PARK', 3271),
 ('NEAR NORTH SIDE', 3362),
 ('AVONDALE', 3640),
 ('WEST ELSDON', 3700),
 ('HERMOSA', 3975),
 ('WASHINGTON HEIGHTS', 4006),
 ('SOUTH CHICAGO', 4043),
 ('GREATER GRAND CROSSING', 4051),
 ('ROGERS PARK', 4068),
 ('LINCOLN SQUARE', 4132),
 ('AUBURN GRESHAM', 4175),
 ('WOODLAWN', 4206),
 ('WEST LAWN', 4207),
 ('NORTH PARK', 4210),
 ('KENWOOD', 4287),
 ('UPTOWN', 4388),
 ('SOUTH SHORE', 4543),
 ('GARFIELD RIDGE', 4552),
 ('DUNNING', 4568),
 ('EDGEWATER', 4600),
 ('DOUGLAS', 4670),
 ('ARCHER HEIGHTS', 4823),
 ('CHATHAM', 5042),
 ('NORTH LAWNDALE', 5146),
 ('EAST SIDE', 5305),
 ('EAST GARFIELD PARK', 5337),
 ('LINCOLN PARK', 5615),
 ('WEST ENGLEWOOD', 5946),
 ('NORWOOD PARK', 6469),
 ('ASHBURN', 6483),
 ('ENGLEWOOD', 6832),
 ('ALBANY PARK', 6864),
 ('PORTAGE PARK', 6954),
 ('ROSELAND', 7020),
 ('LAKE VIEW', 7055),
 ('CHICAGO LAWN', 7086),
 ('LOWER WEST SIDE', 7257),
 ('LOGAN SQUARE', 7351),
 ('NORTH CENTER', 7541),
 ('IRVING PARK', 7764),
 ('NEW CITY', 7922),
 ('NEAR WEST SIDE', 7975),
 ('WEST RIDGE', 8197),
 ('HUMBOLDT PARK', 8620),
 ('WEST TOWN', 9429),
 ('BRIGHTON PARK', 9647),
 ('GAGE PARK', 9915),
 ('AUSTIN', 10933),
 ('BELMONT CRAGIN', 14386),
 ('SOUTH LAWNDALE', 14793)]

In [46]:
%%sql

SELECT "community_area_name" , SUM("college_enrollment") as "total_college_enrollment"
FROM Chicago_school_Data
GROUP BY "community_area_name"
ORDER BY "total_college_enrollment"
LIMIT 5;

 * sqlite:///RealWorldData.db
Done.

[('OAKLAND', 140),
 ('FULLER PARK', 531),
 ('BURNSIDE', 549),
 ('OHARE', 786),
 ('LOOP', 871)]

* Schools with lowest safety score

In [48]:
%%sql

SELECT "name_of_school", "safety_score"
FROM Chicago_School_Data
WHERE "safety_score" != 'None'
ORDER BY "safety_score"
LIMIT 5;

 * sqlite:///RealWorldData.db
Done.

[('Edmond Burke Elementary School', 1.0),
 ("Luke O'Toole Elementary School", 5.0),
 ('George W Tilton Elementary School', 6.0),
 ('Foster Park Elementary School', 11.0),
 ('Emil G Hirsch Metropolitan High School', 13.0)]

In [ ]:
conn.close()